nut.lang.Add("cook_it", "%s cooks the %s")
nut.lang.Add("food_uncook", "not cooked.")
nut.lang.Add("food_worst", "utter shit.")
nut.lang.Add("food_reallybad", "black garbage.")
nut.lang.Add("food_bad", "visually burnt.")
nut.lang.Add("food_notgood", "over cooked.")
nut.lang.Add("food_normal", "cooked.")
nut.lang.Add("food_good", "cooked well.")
nut.lang.Add("food_sogood", "delicious.")
nut.lang.Add("food_reallygood", "unbelieveable.")
nut.lang.Add("food_best", "god-likely cooked.")

nut.lang.Add("stove_desc", "Allows you to cook some food.")
nut.lang.Add("stove_name", "Cooking Stove.")